server {
    listen 80;
    server_name localhost;

    location /authorities/ {
        proxy_pass http://authorities-service:3006/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /road-events/ {
        proxy_pass http://road-event-service:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /statistics/ {
        proxy_pass http://statistics-service:3005/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /user-data/ {
        proxy_pass http://user-data-service:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /user-location/ {
        proxy_pass http://user-location-service:3004/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        return 200 'Nginx is up and running!';
        add_header Content-Type text/plain;
    }
}
