export enum RoadEventType {
  ROAD_CLOSURE = 'ROAD_CLOSURE',
  ROAD_CONSTRUCTION = 'ROAD_CONSTRUCTION',
  ROAD_INCIDENT = 'ROAD_INCIDENT',
  ROAD_DEBRIS = 'ROAD_DEBRIS',
  ROAD_WEATHER = 'ROAD_WEATHER',
  ROAD_OTHER = 'ROAD_OTHER',
}
